In [ ]:
'''
Classification models for the metal subgenre data post feature extraction. 
This file is to be run on the features extracted from the metal_feature_extractor.py file, not VGGish.
To use the file, just change the directory to the directory of your project.
'''

In [1]:
import pandas as pd
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
import os
os.chdir('C:\\Users\\blake\\OneDrive - The University of Texas at Austin\\Project')

metal_df = pd.read_csv('Data\\metal_features.csv')


In [2]:
print(metal_df.shape)
metal_df = metal_df.dropna()
print(metal_df.shape)

(2008, 64)
(2008, 64)


In [3]:
metal_df = metal_df.drop_duplicates(subset='title', keep="first")
print(metal_df.shape)

(1960, 64)


In [4]:
X = metal_df.drop(columns=['title', 'Unnamed: 0', 'subgenre'])
y = metal_df['subgenre']
print(X)

           tempo  zcr_mean   zcr_var  rmse_mean  rmse_var  centroid_mean   
0     151.999081  0.074351  0.001561   0.114258  0.002752    2181.215203  \
1      66.256010  0.111619  0.004041   0.018642  0.000021    2509.989081   
2     161.499023  0.107580  0.002811   0.084716  0.000365    2343.956293   
3     161.499023  0.110319  0.002615   0.076693  0.000777    2424.316543   
4     151.999081  0.089109  0.001700   0.152179  0.003460    2391.270454   
...          ...       ...       ...        ...       ...            ...   
2003  172.265625  0.179256  0.003895   0.054047  0.000416    3318.041756   
2004   95.703125  0.156924  0.000821   0.159225  0.001927    2455.779320   
2005   89.102909  0.158438  0.000756   0.158723  0.000822    2974.813046   
2006  123.046875  0.144889  0.001550   0.060306  0.000275    2763.773133   
2007   99.384014  0.130489  0.000954   0.139728  0.001106    2393.238356   

       centroid_var  bandwidth_mean  bandwidth_var  contrast_mean  ...   
0     482610.

In [5]:
def label_to_int(label):
    if label == 'alternative':
        return 0
    elif label == 'death':
        return 1
    elif label == 'folk':
        return 2
    elif label == 'glam':
        return 3
    elif label == 'industrial':
        return 4
    elif label == 'metalcore':
        return 5
    elif label == 'nu':
        return 6
    elif label == 'NWOBHM':
        return 7
    elif label == 'progressive':
        return 8
    elif label == 'symphonic':
        return 9
    elif label == 'thrash':
        return 10
    
def calculate_accuracy(model, X, Y):
    accuracy = metrics.accuracy_score(Y, model.predict(X))
    return accuracy
    
y = y.apply(lambda x: label_to_int(x))
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
2003    10
2004    10
2005    10
2006    10
2007    10
Name: subgenre, Length: 1960, dtype: int64


In [6]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size= 0.2, random_state = 1)

print('X_train dimension= ', X_train.shape)
print('X_test dimension= ', X_test.shape)
print('y_train dimension= ', y_train.shape)
print('y_train dimension= ', y_test.shape)

X_train dimension=  (1568, 61)
X_test dimension=  (392, 61)
y_train dimension=  (1568,)
y_train dimension=  (392,)


In [211]:
dtree_model = DecisionTreeClassifier(max_depth=2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)

cm = metrics.confusion_matrix(y_test, dtree_predictions)
print(cm)

[[27  3  1  0  0  0  9  0  0  0  0]
 [10 26  1  0  0  0  7  0  0  0  0]
 [11  1 25  0  0  0 14  0  0  0  0]
 [ 6  1 12  0  0  0  2  0  0  0  0]
 [15  7  1  0  0  0 14  0  0  0  0]
 [30  3  0  0  0  0 13  0  0  0  0]
 [ 5  7  1  0  0  0 18  0  0  0  0]
 [ 6  4  0  0  0  0 10  0  0  0  0]
 [26  7  1  0  0  0 11  0  0  0  0]
 [26  1  3  0  0  0  1  0  0  0  0]
 [23  2  3  0  0  0  8  0  0  0  0]]


In [26]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state = 0)
  

In [54]:

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 10).fit(X_train, y_train)
accuracy = knn.score(X_test, y_test)
print(accuracy)

knn_predictions = knn.predict(X_test) 
cm = metrics.confusion_matrix(y_test, knn_predictions)
print(cm)

0.17729083665338646
[[ 8 10  4  2  1  5  7  1 14  1  0]
 [12 17  6  1  4  5  0  1  4  0  5]
 [ 7  1 21  2  6  8  5  0  2  1  8]
 [ 1  2 10  5  3  3  2  0  1  1  4]
 [ 3  3 17  1 10  8  2  1  3  0  1]
 [ 9  5 12  0  6  5  2  2  9  0  2]
 [ 8  7  4  1  4  3  7  1  7  0  1]
 [ 1  3  1  1  1  1  6  0  3  0  1]
 [15 11  5  0  1  7  7  1  9  1  3]
 [ 3  8  6  2  2  1  2  1  3  2  4]
 [ 5  9 11  2  2  5  4  1  1  0  5]]


In [57]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state = 0)
  
# training a Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)
  
# accuracy on X_test
accuracy = gnb.score(X_test, y_test)
print(accuracy)
  
# creating a confusion matrix
cm = metrics.confusion_matrix(y_test, gnb_predictions)
print(cm)

0.17928286852589642
[[ 5  1  1  4  1  2  1  2 23 13  0]
 [ 2  9  0  3  0  0  1  1  6 33  0]
 [ 0  0  0 32  2  2  1  1  6 17  0]
 [ 0  1  1 21  2  1  0  0  1  5  0]
 [ 1  0  3  9  0  1  0  1 12 20  2]
 [ 0  0  0  3  0  3  0  2 16 28  0]
 [ 0  2  1  6  1  0  1  5 20  7  0]
 [ 0  0  0  2  1  2  0  4  7  1  1]
 [ 7  0  0  8  2  0  2  4 26 11  0]
 [ 2  0  0  5  1  1  1  0  4 20  0]
 [ 0  0  0  7  0  4  0  2  6 25  1]]


In [9]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.30)
clf = RandomForestClassifier(n_estimators = 1000)  
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

ACCURACY OF THE MODEL:  0.47619047619047616


In [7]:
import tensorflow as tf
from keras import layers
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state = 0)

model=tf.keras.models.Sequential([
        layers.Conv1D(64, 3, activation='relu', input_shape=(X_train.shape[1], 1)),
        layers.MaxPooling1D(2),
        layers.Conv1D(32, 3, activation='relu'),
        layers.MaxPooling1D(2),
        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dense(11, activation='softmax')   
    ])
# Compile the model
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=16, validation_data=(X_test, y_test))



Epoch 1/100
92/92 [==============================] - 1s 4ms/step - loss: 5615.9268 - accuracy: 0.1027 - val_loss: 2494.2158 - val_accuracy: 0.0633
Epoch 2/100
92/92 [==============================] - 0s 2ms/step - loss: 1893.1406 - accuracy: 0.0891 - val_loss: 1289.6982 - val_accuracy: 0.0796
Epoch 3/100
92/92 [==============================] - 0s 2ms/step - loss: 2068.2161 - accuracy: 0.1170 - val_loss: 1833.8900 - val_accuracy: 0.1408
Epoch 4/100
92/92 [==============================] - 0s 2ms/step - loss: 1824.5847 - accuracy: 0.0918 - val_loss: 984.2502 - val_accuracy: 0.0776
Epoch 5/100
92/92 [==============================] - 0s 2ms/step - loss: 945.1339 - accuracy: 0.0884 - val_loss: 837.1351 - val_accuracy: 0.1020
Epoch 6/100
92/92 [==============================] - 0s 2ms/step - loss: 308.2831 - accuracy: 0.0803 - val_loss: 3.0297 - val_accuracy: 0.1184
Epoch 7/100
92/92 [==============================] - 0s 2ms/step - loss: 2.4171 - accuracy: 0.1211 - val_loss: 2.9038 - val_a

In [39]:
from sklearn.neural_network import MLPClassifier
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state = 0)
mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=500, alpha=0.001,solver='sgd', verbose=0,  random_state=21,tol=0.000000001, activation='relu', learning_rate='adaptive')
mlp.fit(X_train, y_train)
print(calculate_accuracy(mlp, X_test, y_test))

0.1


In [30]:
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state = 0)
logreg = LogisticRegression(max_iter=100000)
logreg.fit(X_train, y_train)
print(calculate_accuracy(logreg, X_test, y_test))

0.34285714285714286


c:\Users\blake\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [213]:
import feature_extractor
input_path = 'Data\\girls_girls_girls.wav'
input_features = feature_extractor.extract_features_from_wav_file(input_path)
input_features = input_features.drop(['title'],axis=1)

c:\Users\blake\OneDrive - The University of Texas at Austin\Project\Test Code\feature_extractor.py:11: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_file = librosa.load(audio_path, offset=60.0, duration=30.0)
c:\Users\blake\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


In [214]:
input_pred = clf.predict(input_features)
print(input_pred)

['4']
